//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetoHackatonIncredibleHihgSpeedTeam.Repository
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_HACKATONEntities : DbContext
    {
        public DB_HACKATONEntities()
            : base("name=DB_HACKATONEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TB_CARREIRA_QUALIFICA> TB_CARREIRA_QUALIFICA { get; set; }
        public virtual DbSet<TB_CARREIRAS> TB_CARREIRAS { get; set; }
        public virtual DbSet<TB_EMPRESA> TB_EMPRESA { get; set; }
        public virtual DbSet<TB_EMPRESA_CARREIRA> TB_EMPRESA_CARREIRA { get; set; }
        public virtual DbSet<TB_ESCOLA> TB_ESCOLA { get; set; }
        public virtual DbSet<TB_ESCOLA_QUALIFICA> TB_ESCOLA_QUALIFICA { get; set; }
        public virtual DbSet<TB_QUALIFICACAO> TB_QUALIFICACAO { get; set; }
        public virtual DbSet<TB_USER> TB_USER { get; set; }
        public virtual DbSet<TB_USER_QUALIFICACAO> TB_USER_QUALIFICACAO { get; set; }
    }
}
