//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetoHackatonIncredibleHihgSpeedTeam.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_CARREIRAS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_CARREIRAS()
        {
            this.TB_CARREIRA_QUALIFICA = new HashSet<TB_CARREIRA_QUALIFICA>();
            this.TB_EMPRESA_CARREIRA = new HashSet<TB_EMPRESA_CARREIRA>();
        }
    
        public int ID { get; set; }
        public string NM_NOME { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_CARREIRA_QUALIFICA> TB_CARREIRA_QUALIFICA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_EMPRESA_CARREIRA> TB_EMPRESA_CARREIRA { get; set; }
    }
}
