//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetoHackatonIncredibleHihgSpeedTeam.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_EMPRESA_CARREIRA
    {
        public int ID { get; set; }
        public int ID_EMPRESA { get; set; }
        public int ID_CARREIRA { get; set; }
    
        public virtual TB_CARREIRAS TB_CARREIRAS { get; set; }
        public virtual TB_EMPRESA TB_EMPRESA { get; set; }
    }
}
