//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetoHackatonIncredibleHihgSpeedTeam.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_ESCOLA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_ESCOLA()
        {
            this.TB_ESCOLA_QUALIFICA = new HashSet<TB_ESCOLA_QUALIFICA>();
        }
    
        public int ID { get; set; }
        public string NM_NOME { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_ESCOLA_QUALIFICA> TB_ESCOLA_QUALIFICA { get; set; }
    }
}
