//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetoHackatonIncredibleHihgSpeedTeam.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_USER_QUALIFICACAO
    {
        public int ID { get; set; }
        public int ID_USER { get; set; }
        public int ID_QUALIFICACAO { get; set; }
    
        public virtual TB_QUALIFICACAO TB_QUALIFICACAO { get; set; }
        public virtual TB_USER TB_USER { get; set; }
    }
}
